### ISSUE TITLE
Broken links to github pages.

### ISSUE THREAD

**Issue by likemusic** [arangodb/docs#583]
Seems that default branch has been renamed from `master` to `main`. Therefore all links to github become invalid.

**Comment by dothebart** [comment]
confirmed with i.e. https://github.com/arangodb/docs/blob/main/3.5/administration.md 
Please note that its not the primary intend to browse this via github; its just nice that it sort of works.

**Comment by likemusic** [comment]
I found this issue when try to contribute by button in the top of all pages on the official documentation pages like https://www.arangodb.com/docs/stable/

![image](https://user-images.githubusercontent.com/603401/99442470-7e581880-292a-11eb-8a47-d791d007d2c8.png)

I found in sources above almost 4462 links to github pages started from `https://github.com/arangodb/docs/edit/master/`.
But I didn't make PR with replaced values, because I don't sure that this is the right solution.
I think would be better to rename `main` branch to standard `master` value.

Is anyone know why `master` branch have been renamed to `main`? Is any real reasons exists for this?

**Comment by Simran-B** [comment]
Fixed by https://github.com/arangodb/docs/commit/4d13b83e6e249e0a6927b7f462190ad9c1622f57.
The docs will be republished with this fix in the next few days.

**Comment by Simran-B** [comment]
Regarding the changed name of the default branch, see:

https://sfconservancy.org/news/2020/jun/23/gitbranchname/
https://github.com/github/renaming#readme

**Comment by likemusic** [comment]
@Simran-B Thank you for the clarification about branches renaming. 

Your commit fixed onlyone link in docs but 4 461 broken links still in the docs. This issue is not fixed completely. I will make PR with fix for all links.

**Comment by likemusic** [comment]
@Simran-B Sorry. My previous post is my mistake. All 4 461 broken links to edit page are in generated  `_site` directory.
